spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=secure
    username: secure
    password: helloworld
  jpa:
    show-sql: true
    properties:
      hibernate:
        ejb:
          interceptor: io.github.fdj32.app.dao.CustomInterceptor

